go_import_path: github.com/aead/sf
sudo: required

dist: trusty

language: go

os:
- linux

env:
- ARCH=x86_64
- ARCH=i686

go:
- "1.9.4"
- "1.10"

script:
- diff -au <(gofmt -d .) <(printf "")
- go vet ./...
- go test -v ./...